apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: seaocp-rtk9d
  name: openshift-compute-ca-central-1a
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: seaocp-rtk9d
      machine.openshift.io/cluster-api-machineset: openshift-compute-ca-central-1a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: seaocp-rtk9d
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: openshift-compute-ca-central-1a
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: ""
      providerSpec:
        value:
          ami:
            id: ami-01284e5815ce66a95
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
                encrypted: true
                kmsKeyId: alias/PBMMAccel-EBS-Key-85987D9D
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: OpenShiftSecurityGroups-WorkerInstanceProfile-ZFUKZVLSK5GU
          instanceType: m5.xlarge
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: ca-central-1a
            region: ca-central-1
          securityGroups:
            - filters:
                - name: group-id
                  values:
                    - sg-0180e9c119047e8b7
          subnet:
            filters:
              - name: tag:Name
                values:
                  - App_Dev_aza_net
          tags:
            - name: kubernetes.io/cluster/seaocp-rtk9d
              value: owned
          userDataSecret:
            name: worker-user-data
